### ISSUE TITLE
Data Type for Prometheus

### ISSUE THREAD

**Issue by mariusehr1** [a0s/nvidia-smi-exporter#5]
Hi,

I am trying out your gpu-exporter and I have the following issue : 

I am running on k8s and have made a little helm chart with a daemonset as well as a service.

Trying from an outside container or within the container I successfully access the metrics at http://nvidia-smi-exporter:9454/metrics

I put the following job in my prometheus configuration : 

```
      - job_name: nvidia_gpus
        static_configs:
          - targets:
            - nvidia-smi-exporter:9454
```

I am getting : 

```

Endpoint | State | Labels | Last Scrape | Scrape Duration | Error
-- | -- | -- | -- | -- | --
http://nvidia-smi-exporter:9454/metrics | DOWN | instance="nvidia-smi-exporter:9454"job="nvidia_gpus" | 16.146s | 486.794ms | strconv.ParseFloat: parsing "455.32.00": invalid syntax
```

Am I missing something?

Thanks
Marius
